# fly.toml file for a production-ready Python Gunicorn app

app = 'gemini-bot-sparkling-tree-3169' # <-- Giữ nguyên tên app của bạn
primary_region = 'sin'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

# Phần quan trọng nhất: Ra lệnh cho Fly.io dùng Gunicorn
[processes]
  app = "gunicorn --bind :8080 --workers 1 --threads 8 app:app"

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
